# Generated by Django 4.2.30 on 2026-08-14 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_inventoryitem_businessperformanceentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctvstream',
            name='rtsp_url',
            field=models.CharField(max_length=500, validators=[django.core.validators.URLValidator(message='Enter a valid stream URL, e.g. rtsp://192.168.1.50:554/stream1', schemes=['rtsp', 'rtsps', 'http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='rtsp_url',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator(message='Enter a valid stream URL, e.g. rtsp://192.168.1.50:554/stream1', schemes=['rtsp', 'rtsps', 'http', 'https'])]),
        ),
    ]
